//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemGecmisi
    {
        public int IslemId { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public Nullable<int> KitapNo { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
