//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.Islems = new HashSet<Islem>();
            this.YayineviKitaps = new HashSet<YayineviKitap>();
            this.IslemGecmisis = new HashSet<IslemGecmisi>();
        }
    
        public int KitapId { get; set; }
        public string ISBNNo { get; set; }
        public string KitapAdi { get; set; }
        public Nullable<int> YazarNo { get; set; }
        public Nullable<int> KategoriNo { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> Puan { get; set; }
        public string Aciklama { get; set; }
        public byte[] Resim { get; set; }
        public string Durum { get; set; }
        public string RafNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Islem> Islems { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Yazar Yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YayineviKitap> YayineviKitaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IslemGecmisi> IslemGecmisis { get; set; }
    }
}
